### ISSUE TITLE
Wind gust direction not recorded

### ISSUE THREAD

**Issue by thkargas** [poblabs/weewx-socketlogger#1]
Added:
        _packet['windGustDir'] = float( data["windDir"] )
at line 139 and weewx records windGustDir in the archive table properly.

**Comment by poblabs** [comment]
The packet `windDir` and `windGustDir` use the same data values?

**Comment by thkargas** [comment]
yes, but since the ip observer reports every 14 seconds, weewx will keep
the windGustDir on the time of the maximum gust wind, while the windDir
stored in the archive will be the mean of all the values of the integral
period (eg 300 seconds). So in the end you will see in the archive table,
that on each record, the values of windDir and windGustDir are different.

**Comment by poblabs** [comment]
Ok that makes sense. Thanks for explaining it! I'll add it to the driver.

**Comment by poblabs** [comment]
Added in 74630e63ebbdbbb8468e463124fab268db328255
