### ISSUE TITLE
Is there some reason you haven't pushed this driver upstream into WeeWX?

### ISSUE THREAD

**Issue by jgettys** [poblabs/weewx-socketlogger#2]
Ethernet devices are often more convenient than USB.... So I bought a 1400IP.

But almost despaired of using it, until I saw your blog entry.

Is there some reason you haven't pushed this driver up stream?

**Comment by poblabs** [comment]
Glad this got your 1400IP working for you! It's a great station so long as you can control the data :) Another problem I see with the ObserverIP is that it needs to be rebooted once every few weeks. For that I've put it on a remote controlled power outlet so I can reboot it when I notice there's no data coming through. 

I guess there's no reason why I haven't tried to submit it to weewx. It's not an official driver, so there's no way to "push" it.... but i suppose I could ask the team if they think it's something that should be packaged and included?

**Comment by jgettys** [comment]
How do you think drivers become official?  It would have been much easier to find; in fact, I spent hours until I stumbled onto it.  And an Ethernet connected weather station is much easier to deal with for many people than USB.

My 1400IP has been working like a champ without rebooting.  Sounds like something isn't right with your 1200.

I haven't finished the install, but will this week.  I did get it sending data to a web server, so I'm pretty sure it should work.  Nothing like a secure device ;-).

**Comment by poblabs** [comment]
Yeah I won't disagree there might be something wrong with mine. But a remote reboot is well within my nerd wheelhouse! :) 

I asked weewx what they thought and initial reaction seemed like they weren't too keen on including it. It's a bit more advanced of a driver than just "plug and play", and it sounds like they have other drivers for the ObserverIP (which I've tried, and failed, which is why I made this driver). 

Nevertheless, it hasn't been explicitly "denied". We'll see where it goes. https://groups.google.com/forum/#!topic/weewx-development/LhAwLeC-vok

**Comment by jgettys** [comment]
On Mon, Jan 30, 2017 at 4:14 PM, poblabs <notifications@github.com> wrote:

> Yeah I won't disagree there might be something wrong with mine. But a
> remote reboot is well within my nerd wheelhouse! :)
>

​Heh.  But for my use, I need a reliable weather station (automated
telescope observation).  My 1400IP has worked like a champ since initial
installation.
​


> I asked weewx what they thought and initial reaction seemed like they
> weren't too keen on including it. It's a bit more advanced of a driver than
> just "plug and play", and it sounds like they have other drivers for the
> ObserverIP (which I've tried, and failed, which is why I made this driver).
>
> Nevertheless, it hasn't been denied. We'll see where it goes.
> https://groups.google.com/forum/#!topic/weewx-development/LhAwLeC-vok
>

​I'll try to chime in.
                                     - Jim
​
